Загрузил 2 лабу
rstu-web-labs/Lab-2_Infra_and_Docker pull request #19
Opened 2024-03-06 08:10 UTC by Kzefnde

2024-03-14 12:37 UTC, kapkaevandrey requested changes
А что проверять?

2024-03-14 14:54 UTC, Kzefnde commented
Так у меня же папка infrostructure загружена

2024-03-14 17:09 UTC, kapkaevandrey requested changes
Добавьте volumes к сервисам **redis** и **postgres**

2024-03-24 09:30 UTC, kapkaevandrey approved these changes
Отлично.

2024-03-24 09:31 UTC, closed without merging